spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: myuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true